version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes: # delete for production
      - ./backend:/app

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: leetcode
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "15432:5432"

volumes:
  pgdata:
