"""add selected_repo to users

Revision ID: a37610476ce3
Revises: 3941b5ea8743
Create Date: 2025-04-11 17:07:29.751848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a37610476ce3'
down_revision: Union[str, None] = '3941b5ea8743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('selected_repo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'selected_repo')
    # ### end Alembic commands ###
